import search
import time
import numpy as np
from scipy.sparse import csr_matrix, coo_matrix


with open("cdr3s.txt") as fh:
	mixed_seqs = fh.readlines()[0:1000]
#reps=20000

#mixed_seqs = ['CACADLGAYPDKLIF','CACDALLAYTDKLIF','CACDAVGDTLDKLIF','CACDDVTEVEGDKLIF','CACDFISPSNWGIQSGRNTDKLIF','CACDILLGDTADKLIF','CACDIVLSGGLDTRQMFF','CACDLLLRQSSTDKLIF','CACDNLSETTDKLIF','CACDPLGTDKLIF','CACDPMGGSGGLSWDTRQMFF','CACDPVLGDTRLTDKLIF','CACDPVQGYSGQNRAYTDKLIF','CACDSILGDTLYTDKLIF','CACDSLTSHTGGFGPDKLIF','CACDSTGDLSSWDTRQMFF','CACDSVESRNVLGDPTTDKLIF','CACDSVLSRDLGDSELIF','CACDTAAGGYASSWDTRQMFF','CACDTAPHGGRTWDTRQMFF','CACDTGGYVNWDTRQMFF','CACDTGRLLGDTADTRQMFF','CACDTIRGFSSWDTRQMFF','CACDTIVAPALDKLIF','CACDTLFLGEDTPTDKLIF','CACDTLGDLSLTAQLFF','CACDTLGDPPHTDKLIF','CACDTLGDYTQSDKLIF','CACDTLGGYPWDTRQMFF','CACDTLGKTDKLIF','CACDTLPLKTGGPLYTDKLIF','CACDTLRLGDPLNTDKLIF','CACDTVALGDTESSWDTRQMFF','CACDTVGAVLGDPKGTDKLIF','CACDTVGDGPDTDKLIF','CACDTVGDTADKLIF','CACDTVGDTHSWDTRQMFF','CACDTVGGSTDKLIF','CACDTVGIPPDKLIF','CACDTVGYGEGDTDKLIF','CACDTVISSNRRGGDKLIF','CACDTVPPGDTGTDKLIF','CACDTVRFTGGYENTDKLIF','CACDYVLGAEDKLIF','CACEGILKSEPLGIDKLIF','CACEMLGHPPGDKLIF','CACVSLDLSYTDKLIF','CALGEIAFRSRTGGPPYTDKLIF','CALGTAYFLRDPGADKLIF','CAVKVPLTSSPREGPTVLHDKLIF']
#mixed_seqs = reps * mixed_seqs
n = len(mixed_seqs)

svec1 = list(mixed_seqs)
svec2 = list(mixed_seqs)
start = time.time()
mv = search.lv_rect2(svec1 = svec2, svec2 = svec1, n1 = n, n2 = n)
end =  time.time()
cy_time = end - start

dists = np.asarray(mv)

print(dists)
print(dists.shape) 
print("Search time (Cython) = {}".format(cy_time))
# how many are within LV 4



